// <auto-generated/>
using AtlassianClient.Rest.Api.Three.Worklog.Deleted;
using AtlassianClient.Rest.Api.Three.Worklog.List;
using AtlassianClient.Rest.Api.Three.Worklog.Updated;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace AtlassianClient.Rest.Api.Three.Worklog {
    /// <summary>
    /// Builds and executes requests for operations under \rest\api\3\worklog
    /// </summary>
    public class WorklogRequestBuilder : BaseRequestBuilder {
        /// <summary>The deleted property</summary>
        public DeletedRequestBuilder Deleted { get =>
            new DeletedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list property</summary>
        public ListRequestBuilder List { get =>
            new ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The updated property</summary>
        public UpdatedRequestBuilder Updated { get =>
            new UpdatedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new WorklogRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorklogRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/3/worklog", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new WorklogRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorklogRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/3/worklog", rawUrl) {
        }
    }
}
