// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace AtlassianClient.Models {
    /// <summary>
    /// The Atlassian provided system rules available.
    /// </summary>
    public class AvailableWorkflowSystemRule : IParsable {
        /// <summary>The rule description.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>List of rules that conflict with this one.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? IncompatibleRuleKeys { get; set; }
#nullable restore
#else
        public List<string> IncompatibleRuleKeys { get; set; }
#endif
        /// <summary>Whether the rule can be added added to an initial transition.</summary>
        public bool? IsAvailableForInitialTransition { get; set; }
        /// <summary>Whether the rule is visible.</summary>
        public bool? IsVisible { get; set; }
        /// <summary>The rule name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The rule key.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RuleKey { get; set; }
#nullable restore
#else
        public string RuleKey { get; set; }
#endif
        /// <summary>The rule type.</summary>
        public AvailableWorkflowSystemRule_ruleType? RuleType { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static AvailableWorkflowSystemRule CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new AvailableWorkflowSystemRule();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"description", n => { Description = n.GetStringValue(); } },
                {"incompatibleRuleKeys", n => { IncompatibleRuleKeys = n.GetCollectionOfPrimitiveValues<string>()?.ToList(); } },
                {"isAvailableForInitialTransition", n => { IsAvailableForInitialTransition = n.GetBoolValue(); } },
                {"isVisible", n => { IsVisible = n.GetBoolValue(); } },
                {"name", n => { Name = n.GetStringValue(); } },
                {"ruleKey", n => { RuleKey = n.GetStringValue(); } },
                {"ruleType", n => { RuleType = n.GetEnumValue<AvailableWorkflowSystemRule_ruleType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("description", Description);
            writer.WriteCollectionOfPrimitiveValues<string>("incompatibleRuleKeys", IncompatibleRuleKeys);
            writer.WriteBoolValue("isAvailableForInitialTransition", IsAvailableForInitialTransition);
            writer.WriteBoolValue("isVisible", IsVisible);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("ruleKey", RuleKey);
            writer.WriteEnumValue<AvailableWorkflowSystemRule_ruleType>("ruleType", RuleType);
        }
    }
}
