// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AtlassianClient.Models {
    /// <summary>Whether the function supports both single and list value operators.</summary>
    public enum FunctionReferenceData_supportsListAndSingleValueOperators {
        [EnumMember(Value = "true")]
        True,
        [EnumMember(Value = "false")]
        False,
    }
}
