// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AtlassianClient.Models {
    /// <summary>The keyword that is the operand value.</summary>
    public enum KeywordOperand_keyword {
        [EnumMember(Value = "empty")]
        Empty,
    }
}
