// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace AtlassianClient.Models {
    /// <summary>
    /// Details of a notification scheme event.
    /// </summary>
    public class NotificationSchemeEventDetails : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ID of the event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public NotificationSchemeEventTypeId? Event { get; set; }
#nullable restore
#else
        public NotificationSchemeEventTypeId Event { get; set; }
#endif
        /// <summary>The list of notifications mapped to a specified event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<NotificationSchemeNotificationDetails>? Notifications { get; set; }
#nullable restore
#else
        public List<NotificationSchemeNotificationDetails> Notifications { get; set; }
#endif
        /// <summary>
        /// Instantiates a new NotificationSchemeEventDetails and sets the default values.
        /// </summary>
        public NotificationSchemeEventDetails() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static NotificationSchemeEventDetails CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new NotificationSchemeEventDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"event", n => { Event = n.GetObjectValue<NotificationSchemeEventTypeId>(NotificationSchemeEventTypeId.CreateFromDiscriminatorValue); } },
                {"notifications", n => { Notifications = n.GetCollectionOfObjectValues<NotificationSchemeNotificationDetails>(NotificationSchemeNotificationDetails.CreateFromDiscriminatorValue)?.ToList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<NotificationSchemeEventTypeId>("event", Event);
            writer.WriteCollectionOfObjectValues<NotificationSchemeNotificationDetails>("notifications", Notifications);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
