// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AtlassianClient.Models {
    /// <summary>The default assignee when creating issues for this project.</summary>
    public enum Project_assigneeType {
        [EnumMember(Value = "PROJECT_LEAD")]
        PROJECT_LEAD,
        [EnumMember(Value = "UNASSIGNED")]
        UNASSIGNED,
    }
}
