// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AtlassianClient.Models {
    /// <summary>The type of role actor.</summary>
    public enum RoleActor_type {
        [EnumMember(Value = "atlassian-group-role-actor")]
        AtlassianGroupRoleActor,
        [EnumMember(Value = "atlassian-user-role-actor")]
        AtlassianUserRoleActor,
    }
}
