// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace AtlassianClient.Models {
    /// <summary>
    /// The IDs of the screens for the screen types of the screen scheme.
    /// </summary>
    public class ScreenTypes : IParsable {
        /// <summary>The ID of the create screen.</summary>
        public long? Create { get; set; }
        /// <summary>The ID of the default screen. Required when creating a screen scheme.</summary>
        public long? Default { get; set; }
        /// <summary>The ID of the edit screen.</summary>
        public long? Edit { get; set; }
        /// <summary>The ID of the view screen.</summary>
        public long? View { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ScreenTypes CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ScreenTypes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"create", n => { Create = n.GetLongValue(); } },
                {"default", n => { Default = n.GetLongValue(); } },
                {"edit", n => { Edit = n.GetLongValue(); } },
                {"view", n => { View = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("create", Create);
            writer.WriteLongValue("default", Default);
            writer.WriteLongValue("edit", Edit);
            writer.WriteLongValue("view", View);
        }
    }
}
