// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace AtlassianClient.Models {
    /// <summary>
    /// The statuses associated with this workflow.
    /// </summary>
    public class StatusLayoutUpdate : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The starting point for the statuses in the workflow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public WorkflowLayout? Layout { get; set; }
#nullable restore
#else
        public WorkflowLayout Layout { get; set; }
#endif
        /// <summary>The properties for this status layout.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public StatusLayoutUpdate_properties? Properties { get; set; }
#nullable restore
#else
        public StatusLayoutUpdate_properties Properties { get; set; }
#endif
        /// <summary>A unique ID which the status will use to refer to this layout configuration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusReference { get; set; }
#nullable restore
#else
        public string StatusReference { get; set; }
#endif
        /// <summary>
        /// Instantiates a new StatusLayoutUpdate and sets the default values.
        /// </summary>
        public StatusLayoutUpdate() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static StatusLayoutUpdate CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new StatusLayoutUpdate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"layout", n => { Layout = n.GetObjectValue<WorkflowLayout>(WorkflowLayout.CreateFromDiscriminatorValue); } },
                {"properties", n => { Properties = n.GetObjectValue<StatusLayoutUpdate_properties>(StatusLayoutUpdate_properties.CreateFromDiscriminatorValue); } },
                {"statusReference", n => { StatusReference = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<WorkflowLayout>("layout", Layout);
            writer.WriteObjectValue<StatusLayoutUpdate_properties>("properties", Properties);
            writer.WriteStringValue("statusReference", StatusReference);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
