// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AtlassianClient.Models {
    /// <summary>The user account type. Can take the following values: *  `atlassian` regular Atlassian user account *  `app` system account used for Connect applications and OAuth to represent external systems *  `customer` Jira Service Desk account representing an external service desk</summary>
    public enum User_accountType {
        [EnumMember(Value = "atlassian")]
        Atlassian,
        [EnumMember(Value = "app")]
        App,
        [EnumMember(Value = "customer")]
        Customer,
        [EnumMember(Value = "unknown")]
        Unknown,
    }
}
