// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace AtlassianClient.Models {
    /// <summary>
    /// Details of workflow transition rules.
    /// </summary>
    public class WorkflowRulesSearchDetails : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>List of workflow rule IDs that do not belong to the workflow or can not be found.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? InvalidRules { get; set; }
#nullable restore
#else
        public List<Guid?> InvalidRules { get; set; }
#endif
        /// <summary>List of valid workflow transition rules.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<WorkflowTransitionRules>? ValidRules { get; set; }
#nullable restore
#else
        public List<WorkflowTransitionRules> ValidRules { get; set; }
#endif
        /// <summary>The workflow ID.</summary>
        public Guid? WorkflowEntityId { get; set; }
        /// <summary>
        /// Instantiates a new WorkflowRulesSearchDetails and sets the default values.
        /// </summary>
        public WorkflowRulesSearchDetails() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static WorkflowRulesSearchDetails CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new WorkflowRulesSearchDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"invalidRules", n => { InvalidRules = n.GetCollectionOfPrimitiveValues<Guid?>()?.ToList(); } },
                {"validRules", n => { ValidRules = n.GetCollectionOfObjectValues<WorkflowTransitionRules>(WorkflowTransitionRules.CreateFromDiscriminatorValue)?.ToList(); } },
                {"workflowEntityId", n => { WorkflowEntityId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<Guid?>("invalidRules", InvalidRules);
            writer.WriteCollectionOfObjectValues<WorkflowTransitionRules>("validRules", ValidRules);
            writer.WriteGuidValue("workflowEntityId", WorkflowEntityId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
