// <auto-generated/>
using AtlassianClient.Rest.Api.Three.User.Assignable.MultiProjectSearch;
using AtlassianClient.Rest.Api.Three.User.Assignable.Search;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace AtlassianClient.Rest.Api.Three.User.Assignable {
    /// <summary>
    /// Builds and executes requests for operations under \rest\api\3\user\assignable
    /// </summary>
    public class AssignableRequestBuilder : BaseRequestBuilder {
        /// <summary>The multiProjectSearch property</summary>
        public MultiProjectSearchRequestBuilder MultiProjectSearch { get =>
            new MultiProjectSearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public SearchRequestBuilder Search { get =>
            new SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new AssignableRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AssignableRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/3/user/assignable", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new AssignableRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AssignableRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/3/user/assignable", rawUrl) {
        }
    }
}
