// <auto-generated/>
using AtlassianClient.Rest.Api.Three.VersionNamespace.Item.Mergeto.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace AtlassianClient.Rest.Api.Three.VersionNamespace.Item.Mergeto {
    /// <summary>
    /// Builds and executes requests for operations under \rest\api\3\version\{id}\mergeto
    /// </summary>
    public class MergetoRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the AtlassianClient.rest.api.Three.version.item.mergeto.item collection</summary>
        /// <param name="position">The ID of the version to merge into.</param>
        public WithMoveIssuesToItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("moveIssuesTo", position);
            return new WithMoveIssuesToItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new MergetoRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MergetoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/3/version/{id}/mergeto", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new MergetoRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MergetoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/3/version/{id}/mergeto", rawUrl) {
        }
    }
}
