// <auto-generated/>
using AtlassianClient.Rest.Api.Three.Universal_avatar.View.TypeNamespace;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace AtlassianClient.Rest.Api.Three.Universal_avatar.View {
    /// <summary>
    /// Builds and executes requests for operations under \rest\api\3\universal_avatar\view
    /// </summary>
    public class ViewRequestBuilder : BaseRequestBuilder {
        /// <summary>The type property</summary>
        public TypeRequestBuilder Type { get =>
            new TypeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new ViewRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ViewRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/3/universal_avatar/view", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new ViewRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ViewRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/3/universal_avatar/view", rawUrl) {
        }
    }
}
