// <auto-generated/>
using AtlassianClient.Rest.Api.Three.Universal_avatar.View.TypeNamespace.Item.Owner.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace AtlassianClient.Rest.Api.Three.Universal_avatar.View.TypeNamespace.Item.Owner {
    /// <summary>
    /// Builds and executes requests for operations under \rest\api\3\universal_avatar\view\type\{type}\owner
    /// </summary>
    public class OwnerRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the AtlassianClient.rest.api.Three.universal_avatar.view.type.item.owner.item collection</summary>
        /// <param name="position">The ID of the project or issue type the avatar belongs to.</param>
        public WithEntityIdItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("entityId", position);
            return new WithEntityIdItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new OwnerRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OwnerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/3/universal_avatar/view/type/{type}/owner", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new OwnerRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OwnerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/3/universal_avatar/view/type/{type}/owner", rawUrl) {
        }
    }
}
